//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attandance
    {
        public decimal id { get; set; }
        public Nullable<System.DateTime> AttandanceDate { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
