//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challan
    {
        public Challan()
        {
            this.ChallanToFeeHeads = new HashSet<ChallanToFeeHead>();
        }
    
        public decimal Id { get; set; }
        public Nullable<int> SId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<bool> PaidFlag { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual ICollection<ChallanToFeeHead> ChallanToFeeHeads { get; set; }
    }
}
