//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Exam()
        {
            this.ExamResults = new HashSet<ExamResult>();
        }
    
        public decimal Id { get; set; }
        public Nullable<decimal> ExamTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> ExamSectionId { get; set; }
        public Nullable<decimal> CourseId { get; set; }
        public Nullable<int> TotalMarks { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ExamType ExamType { get; set; }
        public virtual Section Section { get; set; }
        public virtual ICollection<ExamResult> ExamResults { get; set; }
    }
}
