//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeHead
    {
        public FeeHead()
        {
            this.ChallanToFeeHeads = new HashSet<ChallanToFeeHead>();
            this.StudentToFeeHeads = new HashSet<StudentToFeeHead>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual ICollection<ChallanToFeeHead> ChallanToFeeHeads { get; set; }
        public virtual ICollection<StudentToFeeHead> StudentToFeeHeads { get; set; }
    }
}
