//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolSystemEntities1 : DbContext
    {
        public SchoolSystemEntities1()
            : base("name=SchoolSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Attandance> Attandances { get; set; }
        public DbSet<Challan> Challans { get; set; }
        public DbSet<Class> Classes { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<Exam> Exams { get; set; }
        public DbSet<ExamResult> ExamResults { get; set; }
        public DbSet<ExamType> ExamTypes { get; set; }
        public DbSet<FeeHead> FeeHeads { get; set; }
        public DbSet<Grade> Grades { get; set; }
        public DbSet<MonthlyType> MonthlyTypes { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WeeklyType> WeeklyTypes { get; set; }
        public DbSet<ChallanToFeeHead> ChallanToFeeHeads { get; set; }
        public DbSet<StudentToFeeHead> StudentToFeeHeads { get; set; }
    }
}
