//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyType
    {
        public int Id { get; set; }
        public Nullable<bool> January { get; set; }
        public Nullable<bool> Feburary { get; set; }
        public Nullable<bool> March { get; set; }
        public Nullable<bool> April { get; set; }
        public Nullable<bool> May { get; set; }
        public Nullable<bool> June { get; set; }
        public Nullable<bool> July { get; set; }
        public Nullable<bool> August { get; set; }
        public Nullable<bool> September { get; set; }
        public Nullable<bool> October { get; set; }
        public Nullable<bool> November { get; set; }
        public Nullable<bool> December { get; set; }
    }
}
