//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.Exams = new HashSet<Exam>();
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> ClassId { get; set; }
        public string Description { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
