//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Attandances = new HashSet<Attandance>();
            this.Challans = new HashSet<Challan>();
            this.ExamResults = new HashSet<ExamResult>();
            this.StudentToFeeHeads = new HashSet<StudentToFeeHead>();
        }
    
        public int id { get; set; }
        public string RollNumber { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Religion { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<Attandance> Attandances { get; set; }
        public virtual ICollection<Challan> Challans { get; set; }
        public virtual ICollection<ExamResult> ExamResults { get; set; }
        public virtual Section Section { get; set; }
        public virtual ICollection<StudentToFeeHead> StudentToFeeHeads { get; set; }
    }
}
