//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyType
    {
        public int Id { get; set; }
        public Nullable<bool> FirstWeek { get; set; }
        public Nullable<bool> SecondWeek { get; set; }
        public Nullable<bool> ThirdWeek { get; set; }
        public Nullable<bool> ForthWeek { get; set; }
    }
}
